web:
  build: .
  links:
    - db
  ports:
    - "80:80"
  volumes:
    - "/home/enic/www/captura_manzanillo:/var/www"
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_USER: dev
    MYSQL_PASSWORD: 12345
    MYSQL_DATABASE: myapp
